server {
    listen 80;
    server_name localhost;

    # Onde os arquivos compilados estão armazenados
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Fallback para rotas SPA (Single Page Application)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache de arquivos estáticos (CSS, JS, Imagens, Fontes)
    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public, max-age=2592000, immutable";
    }

    # Desabilitar cache explícito para o Service Worker e Manifests (PWA Offline First)
    location ~* (sw\.js|manifest\.webmanifest|manifest\.json|workbox-.*\.js)$ {
        expires -1;
        access_log off;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
